CREATE TABLE [dbo].[CompanyEFTDetail]
(
	EFTId INT NOT NULL PRIMARY KEY IDENTITY,
	Bank NVARCHAR(100) NOT NULL,
	AccountType NVARCHAR(50) NOT NULL,
	AccountNumber NVARCHAR(25) NOT NULL,
	BranchCode NVARCHAR(15) NOT NULL
)
